spring:
  application:
    name: docs
  liquibase:
    enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/docs
  jpa:
    properties.hibernate.generate_statistics: false
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

liquibase.default.db.schema: "docs"

logging:
  file:
    path: ./logs
  level:
    ROOT: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 60

server:
  port: 8059
